version: '3.9'
services: 
  django:
    build: .
    ports:
      - 8000:8000
    volumes:  
      - .:/app
  db:
    image: postgres
    ports:
      - 5431:5432
    volumes:
      - ./database:/var/lib/postgresql/data/
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres