# Generated by Django 4.2.13 on 2024-06-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Propiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("pais", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=50)),
                ("codigo_postal", models.PositiveIntegerField()),
                ("superficie", models.PositiveIntegerField()),
                ("ciudad", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CASA", "Casa"),
                            ("APTO", "Apartamento"),
                            ("OFICINA", "Oficina"),
                            ("OTRO", "OTRO"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
